TRUNCATE project_links, projects, skills, titles RESTART IDENTITY CASCADE;

INSERT INTO projects (project, img_path, bio, project_date) VALUES
(
  'Game Tracker',
  '/imgs/fullstack.png',
  'This is a full stack website using PREN build. The front end leverages REACT, HTML, CSS, and JavaScript to deliver a fast, responsive, and dynamic user experience, while the back end is powered by Express.js to handle server-side logic and API interactions.',
  '2026-05-01'
),
(
  'Current Personal Website',
  '/imgs/CurrentWP.png',
  'This personal website is built using a modern full-stack JavaScript approach. The front end leverages Vite, HTML, CSS, and JavaScript to deliver a fast, responsive, and dynamic user experience, while the back end is powered by Express.js to handle server-side logic and API interactions.',
  '2026-03-01'
),
(
  'Anime Browser',
  '/imgs/AnimeBrowser.png',
  'Anime Browser built with vanilla JavaScript (ES6+) that allows users to search for anime titles and view detailed information in a dynamic modal interface.This project focuses on strengthening core front-end fundamentals without using frameworks.',
  '2026-02-01'
),
(
  'Black Jack',
  '/imgs/BlackJack.png',
  'For this solo project, I built a command-line Blackjack game using JavaScript, applying object-oriented programming with classes and synchronous prompts for user interaction. The game simulates real Blackjack logic, including dealing cards, calculating scores, and handling player decisions. This project helped me deepen my understanding of classes, game state management, and control flow while building a fully interactive experience',
  '2025-12-01'
),
(
  'First Static Website',
  '/imgs/firstWebsite.png',
  'For this solo project, I built a personal portfolio website from scratch using HTML and CSS. The site showcases my skills, projects, and personality while giving me hands-on experience with responsive design and real-world web development. Through this project, I strengthened my understanding of layout, styling, and problem-solving, and created a portfolio I can continue to grow as I advance in my career.',
  '2026-01-01'
),
(
  'Sample Hotel Reservations (Java)',
  '/imgs/JavaHotelRes.png',
  'In this project, I worked in a pair to build a Java console application that consumes a RESTful API to manage hotel reservations. We implemented functionality to add, update, and delete reservations using Spring''s RestTemplate with POST, PUT, and DELETE requests. The project emphasized creating HTTP entities, handling API errors through exception handling and logging, and debugging REST interactions. Collaborating with a partner helped strengthen my understanding of RESTful services and real-world backend communication.',
  '2025-11-01'
),
(
  'Rock Paper Scissors Command Line Interface',
  '/imgs/RPSCLI.png',
  'CLI Rock-Paper-Scissors is a command-line game that emulates the feel of classic arcade-style games. It features simple controls, fast gameplay, and clear win/lose logic, focusing on user interaction and game flow without a graphical interface. The project highlights core programming concepts like input handling, game state management, and conditional logic—all wrapped in a retro, emulator-inspired experience.',
  '2026-01-01'
),
(
  'Rhythm Revolvers',
  '/imgs/RhythmRevolvers.png',
  'This project is shaping up to be a rhythm-based shooting game where timing is everything. The goal is to blend fast-paced shooting with music-driven mechanics across a variety of themes such as zombies, aliens, and nightclub shootouts. Weapons and playstyles will evolve with difficulty, ranging from simple directional inputs to full keyboard mastery.',
  '2026-04-01'
),
(
  'Marcy Nexus',
  '/imgs/marcyNexus.png',
  'Marcy Nexus is the digital hub for The Marcy Lab School, a one-year tuition-free fellowship that transforms ambitious young adults from underrepresented communities into professional software engineers. The site showcases the program, alumni stories, capstones, and community resources.',
  '2026-05-01'
),
(
  'Quantum Lab',
  '/imgs/QLab.png',
  'Quantum Lab is an interactive, futuristic-themed web experience that guides users through a branching onboarding journey with distinct paths for new and returning users.',
  '2026-06-01'
);

INSERT INTO project_links (project_id, type, url) VALUES
(1, 'GitHub',   'https://github.com/The-Marcy-Lab-School-Assignments/full-stack-project-remix-gjromero6906'),
(1, 'LiveLink', 'https://full-stack-project-remix-gjromero6906.onrender.com'),
(2, 'GitHub',   'https://github.com/gjromero6906/personal-website'),
(2, 'LiveLink', 'https://guadalupejromero.onrender.com'),
(3, 'GitHub',       'https://github.com/Guadalupe-Ian-mls/mod-4-Project'),
(3, 'LiveLink',     'https://guadalupe-ian-mls.github.io/mod-4-Project/'),
(3, 'Presentation', 'https://docs.google.com/presentation/d/1kNYsEEEL-sjjHad9OKM4ipTB836zWQmq5zkIj-o3A1w/edit?usp=sharing'),
(4, 'GitHub', 'https://github.com/gjromero6906/BlackJack'),
(5, 'GitHub', 'https://github.com/gjromero6906/GuadalupeRomero.github.io'),
(6, 'GitHub', 'https://github.com/gjromero6906/Consuming_RESTful_APIs_Part_2'),
(7, 'GitHub', 'https://github.com/gjromero6906/Mod-1-Project-Week'),
(8, 'GitHub', 'https://github.com/gjromero6906/Rhythm-Revolvers'),
(9, 'LiveLink', 'https://envelope.build/marcy-nexus/app'),
(9, 'GitHub', 'https://github.com/MarcyNexus/Nexus'),
(10, 'LiveLink', 'https://quantum-lab-4m1g.onrender.com'),
(10, 'GitHub',   'https://github.com/Lumina-Marcy/Quantum-Lab'),
(10, 'Presentation', 'https://www.genspark.ai/slides?project_id=65d1ab68-af51-472d-bc96-e1c9f6709bb7');

INSERT INTO skills (category, sort_order, name) VALUES
('Languages', 1, 'Python'),
('Languages', 1, 'JavaScript'),
('Languages', 1, 'Java'),
('Languages', 1, 'SQL'),
('Languages', 1, 'Bash'),
('Languages', 1, 'HTML'),
('Languages', 1, 'CSS'),
('Languages', 1, 'PostgreSQL'),
('Languages', 1, 'Lua'),
('Frameworks / Libraries / Environments', 2, 'React'),
('Frameworks / Libraries / Environments', 2, 'FastAPI'),
('Frameworks / Libraries / Environments', 2, 'Express'),
('Frameworks / Libraries / Environments', 2, 'Node.js'),
('Frameworks / Libraries / Environments', 2, 'DOM API'),
('Frameworks / Libraries / Environments', 2, 'Jest'),
('Frameworks / Libraries / Environments', 2, 'Knex'),
('Frameworks / Libraries / Environments', 2, 'Löve'),
('Tools', 3, 'Git'),
('Tools', 3, 'GitHub'),
('Tools', 3, 'VS Code'),
('Tools', 3, 'IntelliJ'),
('Tools', 3, 'Postman'),
('Tools', 3, 'Command-Line Interfaces'),
('Tools', 3, 'Maven'),
('Tools', 3, 'Chrome Developer Tools');

INSERT INTO titles (title) VALUES
('Aspiring Full-Stack Developer'),
('Full-Stack Software Engineer in Training'),
('Software Engineer Graduate'),
('Full-Stack Web Developer'),
('JavaScript Developer'),
('React Developer'),
('Node.js Developer'),
('Web Application Developer'),
('Software Developer'),
('Software Engineer'),
('Entry-Level Software Engineer'),
('Junior Software Engineer'),
('Emerging Software Engineer'),
('Aspiring Software Engineer'),
('Full-Stack Engineer'),
('Web Engineer'),
('Application Developer'),
('Application Engineer'),
('Full-Stack Application Developer'),
('Full-Stack Software Developer'),
('JavaScript Engineer'),
('Web Systems Developer'),
('Front-End and Back-End Developer'),
('End-to-End Software Developer'),
('Modern Web Developer'),
('API Developer'),
('Database-Driven Developer'),
('User-Focused Software Developer'),
('Product-Focused Engineer'),
('Problem-Solving Software Engineer'),
('Scalable Application Developer'),
('Full-Stack Application Builder'),
('Web Solutions Developer'),
('Digital Product Developer'),
('Technology Graduate'),
('Software Engineering Graduate'),
('Full-Stack Engineering Graduate'),
('Developer Graduate'),
('Software Development Graduate'),
('Technology Professional'),
('Software Development Professional'),
('Continuous Learning Engineer'),
('Growth-Oriented Software Engineer'),
('User-Centered Developer'),
('Solutions-Oriented Developer'),
('Innovative Software Developer'),
('Collaborative Software Engineer'),
('Modern JavaScript Developer'),
('React and Node.js Developer'),
('JavaScript Full-Stack Developer'),
('Full-Stack JavaScript Developer'),
('Database and API Developer'),
('Web Application Engineer'),
('Software Solutions Developer'),
('Technical Problem Solver'),
('Software Craftsman'),
('Software Builder'),
('Digital Solutions Engineer'),
('Full-Stack Problem Solver'),
('Application Builder'),
('Software Innovator'),
('Web Technology Developer'),
('Platform Developer'),
('Backend-Focused Full-Stack Developer'),
('Frontend-Focused Full-Stack Developer'),
('Early-Career Software Engineer'),
('Career-Changing Software Engineer'),
('Mission-Driven Software Engineer'),
('Impact-Driven Developer'),
('Community-Focused Software Engineer'),
('Full-Stack Product Developer'),
('Software Systems Developer'),
('Web Systems Engineer'),
('Full-Stack Solutions Engineer'),
('API Integration Specialist'),
('Database Application Developer'),
('User Experience-Focused Developer'),
('Software Development Apprentice'),
('Engineering Graduate'),
('Technology Builder'),
('Digital Experience Developer'),
('Application Systems Developer'),
('Software Technology Graduate'),
('Full-Stack Technology Developer'),
('Modern Application Developer'),
('Cloud-Curious Software Engineer'),
('Open Source Enthusiast'),
('Lifelong Learner in Technology'),
('Emerging Full-Stack Engineer'),
('Aspiring Technology Professional'),
('Web Development Graduate'),
('Software Engineering Professional'),
('Technology Problem Solver'),
('Software Systems Engineer'),
('Full-Stack Software Professional'),
('Product Engineering Enthusiast'),
('Developer and Problem Solver'),
('Technology Innovator'),
('Software Solutions Engineer'),
('Future Software Engineer'),
('Future Full-Stack Engineer'),
('Full-Stack Development Enthusiast'),
('Passionate Software Developer'),
('Driven Software Engineer'),
('Results-Oriented Developer'),
('Adaptable Software Engineer'),
('Creative Problem Solver'),
('Technical Solutions Builder'),
('Engineering-Minded Developer'),
('User-Focused Application Developer'),
('Full-Stack Application Engineer'),
('Software Product Builder'),
('Modern Software Engineer'),
('Web Application Specialist'),
('Data-Driven Developer'),
('Systems Thinking Engineer'),
('Technology Solutions Developer'),
('Developer Advocate for Users'),
('Software Development Enthusiast'),
('Full-Stack Technology Enthusiast'),
('Web Platform Developer'),
('End-to-End Application Developer'),
('Technical Builder'),
('Software Creator'),
('Digital Product Engineer'),
('Application Development Specialist'),
('Future Technology Leader'),
('Community-Driven Engineer'),
('Purpose-Driven Software Engineer'),
('Engineering Problem Solver'),
('Full-Stack Solutions Developer'),
('Software Systems Builder'),
('Modern Technology Developer'),
('Product Development Engineer'),
('Full-Stack Engineering Professional'),
('Web Application Builder'),
('JavaScript Software Engineer'),
('React Software Engineer'),
('Node.js Software Engineer'),
('PostgreSQL Developer'),
('API and Database Developer'),
('Full-Stack Web Engineer'),
('Software Development Engineer'),
('Technology and Innovation Enthusiast'),
('Growth-Minded Software Engineer'),
('Impact-Oriented Developer'),
('Customer-Focused Software Engineer'),
('Engineering Solutions Developer'),
('Technical Product Builder'),
('Full-Stack Career Starter'),
('Aspiring Application Engineer'),
('Emerging Technology Professional'),
('Full-Stack Software Builder'),
('Software Engineering Candidate'),
('Developer in Training'),
('Software Engineer in Training'),
('Full-Stack Developer in Training'),
('Future Full-Stack Software Engineer'),
('Technology-Driven Problem Solver'),
('Full-Stack Development Professional'),
('Modern Web Engineering Enthusiast'),
('Software Engineering Enthusiast'),
('Application Development Enthusiast'),
('Full-Stack Development Graduate'),
('Engineering and Technology Graduate'),
('Web Technology Enthusiast'),
('Software Systems Enthusiast'),
('Digital Solutions Developer'),
('User-Centered Software Engineer'),
('Solution-Focused Engineer'),
('Professional Software Developer'),
('Early-Career Full-Stack Developer'),
('Full-Stack Engineering Candidate'),
('Web Development Professional'),
('Software Development Candidate'),
('Aspiring Product Engineer'),
('Technology-Focused Developer'),
('Application Development Engineer'),
('Full-Stack Innovation Enthusiast'),
('Software Engineering Practitioner'),
('Modern Software Development Enthusiast'),
('Engineering-Focused Problem Solver'),
('Technology and Software Builder'),
('Full-Stack Software Engineering Graduate'),
('Full-Stack Systems Developer'),
('Full-Stack Systems Engineer'),
('Web Application Architect in Training'),
('Software Engineering Learner'),
('Technology Learner and Builder'),
('Software Developer and Problem Solver'),
('Full-Stack Developer and Problem Solver'),
('Engineering Solutions Builder'),
('Digital Product Builder'),
('Software Engineering Graduate Candidate'),
('Full-Stack Engineering Learner'),
('Software Development Learner'),
('Aspiring Technology Innovator'),
('Software Engineering Explorer'),
('Web Development Explorer'),
('Full-Stack Technology Builder'),
('Application Solutions Developer'),
('Technical Solutions Engineer'),
('Technology Creator'),
('Software Creator and Builder'),
('Developer of Digital Solutions'),
('Builder of Web Applications'),
('Builder of Software Solutions'),
('Creator of User-Focused Applications'),
('Engineer of Digital Experiences'),
('Builder of Scalable Applications'),
('Developer of Modern Web Technologies'),
('Creator of Technology Solutions'),
('Builder of End-to-End Applications'),
('Developer of Impactful Software Solutions');
